config/routes.rb
Rails.application.routes.draw do
  comfy_route :cms_admin, path: "/admin"
  # Ensure that this route is defined last
  comfy_route :cms, path: "/"
  root 'static_pages#home'

  scope '/about' do
    get '/ncfa', to: 'static_pages#about_ncfa', as: 'about_ncfa'
    get '/aerm', to: 'static_pages#about_aerm', as: 'about_aerm'
  end

  get '/methodology', to: 'static_pages#methodology'
  get '/collection', to: 'static_pages#collection'
  get '/limitations', to: 'static_pages#limitations'
  get '/ratings', to: 'static_pages#ratings'

  get '/contact', to: 'static_pages#contact', as: 'contact'
  get '/sectors', to: 'static_pages#sectors', as: 'sectors'

  namespace :api do 
    get '/explore/services', to: 'explore#services'
    get '/explore/assets', to: 'explore#assets'
    get '/explore/sectors', to: 'explore#sectors'
  end
  scope '/data' do

    resources :ecosystem_services, only: [:index, :show]
    resources :assets, only: [:index, :show]
    resources :drivers, only: [:index, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/asset.rb
class Asset < ApplicationRecord
  has_many :ecosystem_services_assets_joins
  has_many :ecosystem_services, through: :ecosystem_services_assets_joins

  has_many :assets_drivers_joins
  has_many :drivers, through: :assets_drivers_joins
end

app/models/assets_drivers_join.rb
class AssetsDriversJoin < ApplicationRecord
  belongs_to :asset
  belongs_to :driver
end

app/models/driver.rb
class Driver < ApplicationRecord
  has_many :assets_drivers_joins
  has_many :assets, through: :assets_drivers_joins
end

app/models/ecosystem_service.rb
class EcosystemService < ApplicationRecord
  has_many :materialities
  has_many :production_processes, through: :materiality

  has_many :ecosystem_services_assets_joins
  has_many :assets, through: :ecosystem_services_assets_joins
end

app/models/ecosystem_services_assets_join.rb
class EcosystemServicesAssetsJoin < ApplicationRecord
  belongs_to :ecosystem_service
  belongs_to :asset
end

app/models/materiality.rb
class Materiality < ApplicationRecord
  belongs_to :production_process
  belongs_to :ecosystem_service
end

app/models/production_process.rb
class ProductionProcess < ApplicationRecord
  belongs_to :sub_industry
  has_many :materialities
  has_many :ecosystem_services, through: :materiality
end

app/models/sector.rb
class Sector < ApplicationRecord
  has_many :sub_industries, dependent: :destroy
  has_many :production_processes, through: :sub_industries
end

app/models/sub_industry.rb
class SubIndustry < ApplicationRecord
  belongs_to :sector
  has_many :production_processes, dependent: :destroy
end

app/controllers/api/explore_controller.rb
class Api::ExploreController < ActionController::API
  before_action :set_headers

  def set_headers
    response.headers['Content-Type'] = 'application/json'
  end
  
  def services
    services = EcosystemService.all.includes([:assets, materialities: [:production_process]])

    render json: services.to_json(:only => [:id, :name], :include =>{
                                    :assets => {
                                      :only => [:id, :name] },
                                    :materialities => {
                                      :only => [:id, :rag], :include => {
                                        :production_process => {:only => [:id, :name] } }
                                    }
                                  } ), status: :ok
  end

  def assets
    assets = Asset.all.includes(ecosystem_services: [materialities: [:production_process]]).where(production_process: process_ids)
    
    render json: assets.to_json(:only => [:id, :name], :include => {
                                  :ecosystem_services  => {
                                    :only => [:id, :name], :include => {
                                      :materialities => {
                                        :only => [:id, :rag], :include => {
                                          :production_process => {:only => [:id, :name] }
                                        }
                                      }
                                    }
                                  }
                                }
                               ), status: :ok
  end
  
  def sectors
    sectors = Sector.all.includes(sub_industries: [:production_processes] )

    render json: sectors.to_json(:only => [:id, :name], :include => {
                                   :sub_industries => {
                                     :only => [:id, :name], :include => {
                                       :production_processes => {:only => [:id, :name] }
                                     }
                                   }
                                 } ), status: :ok
  end

  private
  
  def filter_params
    params.permit(:sector_id, :sub_industry_id, :production_processes)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  def index
    @assets = Asset.all
  end

  def show
    @asset = Asset.find(params[:id])
    @materialities = @asset.ecosystem_services.map(&:materialities).flatten(1).uniq(&:production_process)
  end
end

app/controllers/drivers_controller.rb
class DriversController < ApplicationController
  def index
    @drivers = Driver.all
  end

  def show
    @driver = Driver.find(params[:id])
    # look up production processes this driver is 'likely to influence' via assets->services->materialities
    services = EcosystemService.find(@driver.assets.map(&:id))
    @materialities = services.map(&:materialities).flatten(1).uniq(&:production_process)
  end
end

app/controllers/ecosystem_services_controller.rb
class EcosystemServicesController < ApplicationController
  def index
    @services = EcosystemService.all
  end

  def show
    @service = EcosystemService.find(params[:id])
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about_ncfa
  end

  def about_aerm
  end

  def methodology
  end

  def collection
  end

  def limitations
  end

  def ratings
  end

  def explore
  end

  def map
  end

  def sectors
    @sectors = Sector.all
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sector_helper.rb
module SectorHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/application/_materialities.html.erb
  <% im = @materialities.group_by{|m| m.production_process.sub_industry}  %>
  
  <% im.keys.each do |ind| %>

  <table>
    <tr>
      <th><%= ind.name %></th>
      <th> Materiality Rating </th>
      <th> </th>
    </tr>
    <% im[ind].each do |m| %>
    <tr>
      <td><%= m.production_process.name %></td>
      <td><%= m.rag %></td>
      <td><%= m.justification %></td>
    </tr>
    <% end %>
  </table>
  
  <% end %>

app/views/application/_topbar.html.erb
<div >
  
  <ul>
    <strong>About Menu: <em><a href="https://projects.invisionapp.com/share/NPNSQSI2QFM#/screens/318724894">invision</a><em></strong>
    <li>
      <%= link_to 'What is AERM', about_aerm_path %>
    </li>
    <li>
      <%= link_to 'About NCFA', about_ncfa_path %>
    </li>
  </ul>
  <%= link_to 'Explore', '' %>
  
  <ul>
    <strong>Data and Methodology: <em><a href="https://projects.invisionapp.com/share/NPNSQSI2QFM#/screens/318724947">invision</a><em></strong>
    <li>
      <%= link_to 'Methodology', methodology_path %>
    </li>
    <li>
      <%= link_to 'Data Collection', collection_path %>
    </li>
    <li>
      <%= link_to 'Limitations', limitations_path %>
    </li>
    <li>
      <%= link_to 'Ratings', ratings_path %>
    </li>
    <li>
      <%= link_to 'Sectors', sectors_path %>
    </li>
    <li>
      <%= link_to 'Services', ecosystem_services_path  %>
    </li>
    <li>
      <%= link_to 'Drivers', drivers_path %>
    </li>
    <li>
      <%= link_to 'Assets', assets_path  %>
    </li>
  </ul>
  <%= link_to 'Case Studies', '' %>
  <%= link_to 'Contact', contact_path %>

</div>

app/views/asset/index.html.erb
<h1>Asset#index</h1>
<p>Find me in app/views/asset/index.html.erb</p>
<p><a href="https://projects.invisionapp.com/share/NPNSQSI2QFM#/screens/318726068">invision</a></p>
<% @assets.each do |asset| %>
  <p><%= asset.name %></p>
<% end %>

app/views/assets/index.html.erb
<h1>Assets#index</h1>
<p>Find me in app/views/assets/index.html.erb</p>
<p><a href="https://projects.invisionapp.com/share/NPNSQSI2QFM#/screens/318726068">invision</a></p>
<% @assets.each do |asset| %>
  <p><%= link_to asset.name, asset_path(asset.id) %></p>
<% end %>

app/views/assets/show.html.erb
<h1>Assets#index</h1>
<p>Find me in app/views/assets/index.html.erb</p>
<p><a href="https://projects.invisionapp.com/share/NPNSQSI2QFM#/screens/317226205">invision</a></p>
<h1><%= @asset.name %></h1>

Important for:
<ul>
Ecosystem Category
<% @asset.ecosystem_services.each do |service| %>

<li><%= service.name %>

<% end %>
</ul>

Highly material for:

<%= render partial: "materialities", object: @materialities %>

Drivers of Change:

<ul>
<% @asset.name %> ->
<% @asset.drivers.uniq.each do |driver| %>
<li><%= driver.name %> <%= link_to 'View ->', driver_path(driver.id) %></li>
<% end %>
</ul>

app/views/driver/index.html.erb
<h1>Driver#index</h1>
<p>Find me in app/views/driver/index.html.erb</p>
<p><a href="https://projects.invisionapp.com/share/NPNSQSI2QFM#/screens/319019067">invision</a></p>
<% @drivers.each do |driver| %>
  <p><%= driver.name %></p>
<% end %>

app/views/drivers/index.html.erb
<h1>Driver#index</h1>
<p>Find me in app/views/driver/index.html.erb</p>
<p><a href="https://projects.invisionapp.com/share/NPNSQSI2QFM#/screens/319019067">invision</a></p>
<% @drivers.each do |driver| %>
  <p><%= link_to driver.name, driver_path(driver.id) %></p>
<% end %>

app/views/drivers/show.html.erb
<h1>Driver#show</h1>
<p>Find me in app/views/drivers/show.html.erb</p>
<p><a href="https://projects.invisionapp.com/share/NPNSQSI2QFM#/screens/317226179">invision</a></p>
<h1><%= @driver.name %></h1>

<ul>
Influences to assets:
<% ad = @driver.assets_drivers_joins.group_by(&:asset) %>
<% ad.keys.each do |key| %>
<li><%= key.name %></li>
<% end %>
</ul>

Likely to influence:

<%= render partial: "materialities", object: @materialities %>

app/views/ecosystem_service/index.html.erb
<h1>EcosystemService#index</h1>
<p>Find me in app/views/ecosystem_service/index.html.erb</p>
<p><a href="https://projects.invisionapp.com/share/NPNSQSI2QFM#/screens/318725954">invision</a></p>
<% @services.each do |service| %>
  <p><%= service.name %></p>
<% end %>

app/views/ecosystem_services/index.html.erb
<h1>EcosystemService#index</h1>
<p>Find me in app/views/ecosystem_service/index.html.erb</p>
<p><a href="https://projects.invisionapp.com/share/NPNSQSI2QFM#/screens/318725954">invision</a></p>
<% @services.each do |service| %>
  <p><%= link_to service.name, ecosystem_service_path(service.id)  %></p>
<% end %>

app/views/ecosystem_services/show.html.erb
<h1>EcosystemServices#show</h1>
<p>Find me in app/views/ecosystem_services/show.html.erb</p>
<p><a href="https://projects.invisionapp.com/share/NPNSQSI2QFM#/screens/317451457">invision</a></p>
<h1><%= @service.name %></h1>

Natural Capital Assets:
<ul>
  <% @service.assets.each do |asset| %>
  <li>
    <h2><%= asset.name %></h2>
    <ul>
      Drivers of Change:
      <% ad =  asset.assets_drivers_joins.group_by(&:driver) %>
      <% ad.keys.each do |key| %>
      <li><%= key.name %></li>
      <table>
	<tr>
	  <th>Likely Response </th>
	  <th>Effect of variability on services provision</th>
	  <th>Human action or natural variation</th>
	  <th>Timescale</th>
	  <th>Spatial Characteristics</th>
	</tr>
	<% ad[key].each do |adj| %>
	<tr>
	  <td><%= adj.likely_response %></td>
	  <td><%= adj.effect_on_variability %></td>
	  <td><%= adj.human_action_or_natural_variation %></td>
	  <td><%= adj.timescale %></td>
	  <td><%= adj.spatial_characteristics %></td>
	</tr>
	<% end %>
      </table>
      <% end %>
    </ul>
    
  </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NCFA</title>
    <%= csrf_meta_tags %>
    <meta content='width=device-width,initial-scale=1.0' name='viewport'>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application' %>

    <link href='https://api.tiles.mapbox.com/mapbox-gl-js/v0.49.0/mapbox-gl.css' rel='stylesheet' />
    <link href='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v2.3.0/mapbox-gl-geocoder.css' rel='stylesheet' />

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>

    <script src='https://api.tiles.mapbox.com/mapbox-gl-js/v0.49.0/mapbox-gl.js'></script>
    <script src='https://api.mapbox.com/mapbox-gl-js/plugins/mapbox-gl-geocoder/v2.3.0/mapbox-gl-geocoder.min.js'></script>
  </head>

  <body>
    <div id="v-app">
      <%= yield %>
    </div>
  </body>
</html>

app/views/sector/index.html.erb
<h1>Sector#index</h1>
<p>Find me in app/views/sector/index.html.erb</p>
<p><a href="https://projects.invisionapp.com/share/NPNSQSI2QFM#/screens/318725954">invision</a></p>
<% @sectors.each do |sector| %>
  <p><%= sector.name %></p>
<% end %>

app/views/static_pages/about_aerm.html.erb
<h1>StaticPages#about_aerm</h1>
<p>Find me in app/views/static_pages/about_aerm.html.erb</p>
<a href="https://projects.invisionapp.com/share/NPNSQSI2QFM#/screens/318725326">invision</a>

app/views/static_pages/about_ncfa.html.erb
<h1>StaticPages#about_ncfa</h1>
<p>Find me in app/views/static_pages/about_ncfa.html.erb</p>
<a href="https://projects.invisionapp.com/share/NPNSQSI2QFM#/screens/318725385">invision</a>

app/views/static_pages/collection.html.erb
<h1>StaticPages#collection</h1>
<p>Find me in app/views/static_pages/collection.html.erb</p>
<a href="https://projects.invisionapp.com/share/NPNSQSI2QFM#/screens/318726217">invision</a>

app/views/static_pages/contact.html.erb
<h1>StaticPages#contact</h1>
<p>Find me in app/views/static_pages/contact.html.erb</p>
<a href="https://projects.invisionapp.com/share/NPNSQSI2QFM#/screens/318726640">invision</a>

app/views/static_pages/explore.html.erb
<div id="explore">
  <explore-page></explore-page>
</div>

app/views/static_pages/home.html.erb
<div id="home">
  <home-page></home-page>
</div>

app/views/static_pages/limitations.html.erb
<h1>StaticPages#limitations</h1>
<p>Find me in app/views/static_pages/limitations.html.erb</p>
<a href="https://projects.invisionapp.com/share/NPNSQSI2QFM#/screens/319018403">invision</a>

app/views/static_pages/map.html.erb
<div id="map">
  <map-page></map-page>
</div>

app/views/static_pages/methodology.html.erb
<h1>StaticPages#methodology</h1>
<p>Find me in app/views/static_pages/methodology.html.erb</p>
<a href="https://projects.invisionapp.com/share/NPNSQSI2QFM#/screens/318725916">invision</a>

app/views/static_pages/ratings.html.erb
<h1>StaticPages#ratings</h1>
<p>Find me in app/views/static_pages/ratings.html.erb</p>
<a href="https://projects.invisionapp.com/share/NPNSQSI2QFM#/screens/318726123">invision</a>

app/views/static_pages/sectors.html.erb
<h1>Sector#index</h1>
<p>Find me in app/views/sector/index.html.erb</p>
<p><a href="https://projects.invisionapp.com/share/NPNSQSI2QFM#/screens/318725975">invision</a></p>
<% @sectors.each do |sector| %>
  <p><%= sector.name %></p>
<% end %>